### ISSUE TITLE
Sync-ldap fails in v1.4.0

### ISSUE THREAD

**Issue by giesselmann** [ClusterCockpit/cc-backend#314]
Hi,
after updating to v1.4.0 the `--sync-ldap` flag causes an error:
```
[WARNING]  user.go:78: Error while querying usernames
[CRITICAL] /opt/clustercockpit/src/cc-backend/cmd/cc-backend/main.go:153: LDAP sync failed: no such column: user.ldap
```
Database version is 8, without the flag, the service comes up as expected.

**Comment by moebiusband73** [comment]
Thanks for the report.  This is an artefact of renaming the user column in the db schema. We already found another issue caused by that. I will do a more thorough review searching for references on this column and probably do a bugfix release tomorrow.

**Comment by moebiusband73** [comment]
OMG, I must be blind to not have seen that :-(
